name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See https://endoflife.date/nodejs
        node-version:
          - '16'
          - '18'
          - '20'
          - 'lts/*'
        browser:
          - 'chromium'
          - 'firefox'
          - 'webkit'
    name: Node ${{ matrix.node-version }} (${{ matrix.browser }}) tests
    env:
      WORKING_DIRECTORY: ${{ github.workspace }}
      CI: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    # See https://dev.to/ayomiku222/how-to-cache-playwright-browser-on-github-actions-51o6
    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.COMMIT_SHORT_SHA }}

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Install Playwright additional dependencies (for WebKit)
      run: npx playwright install-deps
      if: matrix.browser == 'webkit'

    - name: Generate mock audit report (default options)
      run: cat ${{ github.workspace }}/.playwright/fixtures/npm-audit.json | ./src/index.js --folder ${{ github.workspace }}/.reports --file npm-audit.html

    - name: Run Playwright tests for ${{ matrix.browser }}
      env:
        WEB_BROWSER: ${{ matrix.browser }}
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-nodejs-v${{ matrix.node-version }}
        path: playwright-report/nodejs-v${{ matrix.node-version }}
        retention-days: 15
        overwrite: true
